### ISSUE TITLE
在centos7上docker-compose up -d后出现如下的报错该怎么解决

### ISSUE THREAD

**Issue by TheBeastofwar** [qigpig/MysqlHoneypot#8]
![image](https://github.com/qigpig/MysqlHoneypot/assets/117450378/310f879c-31f9-4e05-bb22-8314bbf21c7b)
防火墙全关了

**Comment by qigpig** [comment]
本项目已停止维护（我太懒了），仅供思路参考，如有需求可以寻找其他由本项目衍生出的同类系统
